function net = add_reg_toss_test(net, id, regNum)
% --------------------------------------------------------------------
net.layers{end+1} = struct('type', 'reg_toss', ...
    'name', sprintf('reg%s', id),...
    'regNum', regNum) ;