function net = add_reg_concat_test(net, id, regSet)
% --------------------------------------------------------------------
net.layers{end+1} = struct('type', 'reg_concat', ...
    'name', sprintf('reg%s', id),...
    'regSet', regSet) ;